package teamgg.database.fields;

public enum RelationshipDBFields {
	ACCOUNT_ID_1, ACCOUNT_ID_2, FIRST_ENCOUNTER_AGAINST, FIRST_ENCOUNTER_WITH, LAST_ENCOUNTER_AGAINST, LAST_ENCOUNTER_WITH, LOST_AGAINST, LOST_WITH, WON_AGAINST, WON_WITH

}
